[workspace]
members = ["crates/card", "tcg"]
resolver = "2"

[workspace.dependencies]
bevy = { version = "0.14.2" }
epithet = { path = "./crates/epithet" }
card = { path = "./crates/card" }
bevy-inspector-egui = "0.26.0"