[package]
name = "tcg"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
epithet = { workspace = true }
card = { workspace = true }
bevy-inspector-egui = "0.26.0"

[dev-dependencies]
bevy = { workspace = true }

[features]
default = ["render"]
render = ["card/render"]