[package]
name = "card"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true }
rand = "0.8.5"
epithet = { workspace = true }

[dev-dependencies]
bevy = { workspace = true }

[features]
default = ["render"]
render = []